Use Tempo's own API instead of Jira REST API
componentK/toggl-tempo-sync pull request #2
Opened 2020-03-06 10:33 UTC by lunaticare

* authenticate Tempo with API token, see ["Using the REST API as an application developer"](https://tempo-io.github.io/tempo-api-docs/)
* use Tempo's own [API](https://tempo-io.github.io/tempo-api-docs/#worklogs)

2020-04-05 16:55 UTC, augsteyer commented
Apologies for the delay, apparently I need to be watching my own repositories to get notifications for them.

I like the support for Cloud API, however, you are substituting the support of Private Server API for Cloud API here. And I kinda need the server support :) 
It would be better to keep both, and create a switch in the config file to use one or the other as they are not the same thing, see their [dev docs](https://www.tempo.io/developers).
e.g. `useTempoCloud: true/false`

Or, if you do not want to bother with extra work, you should adjust the logic in your fork and rename the project to identify your support for Tempo Cloud API only.

You would also want to run the linter to make sure some of the styling is adjusted, e.g.
```
cd [project]
npm i
./node_modules/.bin/eslint -c .eslintrc index.js helpers/ test/
```

2020-04-05 16:59 UTC, augsteyer requested changes

2020-04-05 16:59 UTC, augsteyer commented on index.js
> +}
will need a docblock
e.g.
```
/**
 * A delay for tempo entry loading
 *
 * @param {number} ms
 * @return {Promise<number>}
 */
function sleep (ms) {
  return new Promise(resolve => setTimeout(resolve, ms))
}
```

2020-04-05 16:59 UTC, augsteyer commented on index.js
> +      console.log(issueKey + ' ' + comment)
per linter requirements, template usage: 
```suggestion
      console.log(`${issueKey} ${comment}`)
```

2020-04-05 16:59 UTC, augsteyer commented on index.js
> +      await sleep(Math.random() * 20000)
not quite sure why there is a random delay here

2020-04-05 16:59 UTC, augsteyer commented on index.js
> +      })}
will need to adjust per linter styles as well:
```
      })
    }
```

2022-07-10 18:34 UTC, lunaticare commented
Will close the PR as I no longer use Tempo, and don't have access to test the changes.

2022-07-10 18:34 UTC, closed without merging